# Generated by Django 2.1.3 on 2020-09-29 13:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('private_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fixed_budget', models.IntegerField(blank=True, default=750, null=True)),
                ('hourly_budget', models.IntegerField(blank=True, default=20, null=True)),
                ('payment_filter', models.BooleanField(default=True)),
                ('time_delta', models.IntegerField(blank=True, default=30, null=True)),
                ('job_count', models.IntegerField(blank=True, default=10, null=True)),
                ('notification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'filter',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=400)),
                ('hourly', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, default='', max_length=400)),
                ('budget', models.CharField(blank=True, default='', max_length=400)),
                ('maxBudget', models.FloatField(blank=True, default=0)),
                ('skills', models.CharField(blank=True, default='', max_length=400)),
                ('country', models.CharField(blank=True, default='', max_length=400)),
                ('completedJob', models.IntegerField(default=0)),
                ('memberDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectId', models.CharField(blank=True, default='', max_length=400)),
                ('v_identity', models.BooleanField(default=False)),
                ('v_payment', models.BooleanField(default=False)),
                ('v_deposit', models.BooleanField(default=False)),
                ('v_email', models.BooleanField(default=False)),
                ('v_profile', models.BooleanField(default=False)),
                ('v_phone', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1)),
                ('router', models.CharField(blank=True, default='', max_length=400)),
                ('recruiter', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('check_status', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 21, 38, 7, 780305, tzinfo=utc))),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='NewMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 13, 38, 7, 785303, tzinfo=utc))),
            ],
            options={
                'db_table': 'new_messages',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(blank=True, default='')),
                ('developer', models.CharField(blank=True, choices=[('cf', 'CF'), ('santa', 'Santa'), ('ls', 'LS'), ('balya', 'Balya'), ('cr', 'ChenRi'), ('yd', 'YD')], default='', max_length=400)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('developer', models.CharField(blank=True, choices=[('cf', 'CF'), ('santa', 'Santa'), ('ls', 'LS'), ('balya', 'Balya'), ('cr', 'ChenRi'), ('yd', 'YD')], default='', max_length=400)),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
            options={
                'db_table': 'urls',
            },
        ),
    ]
