# Generated by Django 2.1.3 on 2020-06-26 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=400)),
                ('hourly', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, default='', max_length=400)),
                ('budget', models.CharField(blank=True, default='', max_length=400)),
                ('skills', models.CharField(blank=True, default='', max_length=400)),
                ('country', models.CharField(blank=True, default='', max_length=400)),
                ('completedJob', models.IntegerField(default=0)),
                ('memberDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectId', models.CharField(blank=True, default='', max_length=400)),
                ('v_identity', models.BooleanField(default=False)),
                ('v_payment', models.BooleanField(default=False)),
                ('v_deposit', models.BooleanField(default=False)),
                ('v_email', models.BooleanField(default=False)),
                ('v_profile', models.BooleanField(default=False)),
                ('v_phone', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
