# Generated by Django 2.1.3 on 2020-10-02 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200930_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bidder',
            field=models.ManyToManyField(blank=True, null=True, related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 2, 5, 8, 589896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 18, 5, 8, 595895, tzinfo=utc)),
        ),
    ]
