# Generated by Django 2.1.3 on 2020-06-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='bidder',
            field=models.CharField(blank=True, choices=[('cf', 'CF'), ('santa', 'Santa'), ('ls', 'LS'), ('balya', 'Balya'), ('cr', 'ChenRi'), ('yd', 'YD')], default='', max_length=400),
        ),
    ]
