# Generated by Django 2.1.3 on 2020-10-23 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20201003_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 8, 44, 51, 998089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 8, 44, 52, 4086, tzinfo=utc)),
        ),
    ]
