# Generated by Django 2.1.3 on 2020-06-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200627_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='bid',
            new_name='checked',
        ),
    ]
