# Generated by Django 2.1.3 on 2020-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200627_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='maxBudget',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
