# Generated by Django 2.1.3 on 2020-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201023_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='api.Category'),
        ),
    ]
