# Generated by Django 2.1.3 on 2020-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_maxbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
