# Generated by Django 2.1.3 on 2020-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keys',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
