# Generated by Django 2.1.3 on 2020-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keys',
            field=models.TextField(blank=True, default=''),
        ),
    ]
