# Generated by Django 2.1.3 on 2020-06-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200628_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=400)),
                ('keywords', models.TextField(blank=True, default='')),
                ('developer', models.CharField(blank=True, choices=[('cf', 'CF'), ('santa', 'Santa'), ('ls', 'LS'), ('balya', 'Balya'), ('cr', 'ChenRi'), ('yd', 'YD')], default='', max_length=400)),
                ('category', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'db_table': 'urls',
            },
        ),
    ]
