# Generated by Django 2.1.3 on 2020-06-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('job', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
                ('template', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Template')),
            ],
            options={
                'db_table': 'bids',
            },
        ),
    ]
