# Generated by Django 2.1.3 on 2020-06-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='bidder',
        ),
    ]
