# Generated by Django 2.1.3 on 2020-06-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_job_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
