# Generated by Django 2.1.3 on 2020-06-27 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_template_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
