# Generated by Django 2.1.3 on 2020-06-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_job_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='category',
        ),
    ]
