# Generated by Django 2.1.3 on 2020-06-29 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200629_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keys',
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 18, 36, 23, 660385, tzinfo=utc)),
        ),
    ]
