# Generated by Django 2.1.3 on 2020-06-29 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200629_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='keywords',
        ),
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 18, 46, 50, 750697, tzinfo=utc)),
        ),
    ]
