# Generated by Django 2.1.3 on 2020-06-29 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200629_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 7, 52, 264886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
