# Generated by Django 2.1.3 on 2020-06-29 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200629_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 36, 2, 873365, tzinfo=utc)),
        ),
    ]
