# Generated by Django 2.1.3 on 2020-06-29 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200629_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='category',
        ),
        migrations.AddField(
            model_name='bid',
            name='bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 21, 34, 0, 277260, tzinfo=utc)),
        ),
    ]
