# Generated by Django 2.1.3 on 2020-06-29 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200629_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='bidder',
        ),
        migrations.AddField(
            model_name='job',
            name='bidder',
            field=models.ManyToManyField(to='api.Account'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 0, 54, 21, 172311, tzinfo=utc)),
        ),
    ]
