# Generated by Django 2.1.3 on 2020-06-29 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200630_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 1, 8, 43, 671163, tzinfo=utc)),
        ),
    ]
