# Generated by Django 2.1.3 on 2020-06-29 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200630_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bidder',
            field=models.ManyToManyField(related_name='bots', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 1, 17, 0, 280431, tzinfo=utc)),
        ),
    ]
