# Generated by Django 2.1.3 on 2020-06-29 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200630_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 2, 34, 47, 115308, tzinfo=utc)),
        ),
    ]
