# Generated by Django 2.1.3 on 2020-06-29 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200630_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bidder',
            field=models.ManyToManyField(related_name='bidders', to='api.Account'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='bot',
        ),
        migrations.AddField(
            model_name='job',
            name='bot',
            field=models.ManyToManyField(related_name='bots', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 3, 13, 59, 647288, tzinfo=utc)),
        ),
    ]
