# Generated by Django 2.1.3 on 2020-06-30 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200630_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bidder',
            field=models.ManyToManyField(blank=True, null=True, related_name='bidders', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='job',
            name='bot',
            field=models.ManyToManyField(blank=True, null=True, related_name='bots', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 11, 44, 33, 376610, tzinfo=utc)),
        ),
    ]
