# Generated by Django 2.1.3 on 2020-06-30 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200630_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 17, 29, 51, 861104, tzinfo=utc)),
        ),
    ]
