# Generated by Django 2.1.3 on 2020-06-30 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200630_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 17, 53, 51, 514030, tzinfo=utc)),
        ),
    ]
