# Generated by Django 2.1.3 on 2020-06-30 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200630_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='private_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 1, 31, 50, 89079, tzinfo=utc)),
        ),
    ]
