# Generated by Django 2.1.3 on 2020-06-30 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200701_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fixed_budget',
            field=models.IntegerField(blank=True, default=750, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hourly_budget',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='job_count',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='time_delta',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 1, 46, 10, 220362, tzinfo=utc)),
        ),
    ]
