# Generated by Django 2.1.3 on 2020-06-30 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200701_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 1, 49, 29, 742780, tzinfo=utc)),
        ),
    ]
