# Generated by Django 2.1.3 on 2020-06-30 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200701_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 1, 50, 29, 698794, tzinfo=utc)),
        ),
    ]
