# Generated by Django 2.1.3 on 2020-06-30 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200701_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='countries',
            field=models.ManyToManyField(to='api.Country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 1, 52, 32, 898236, tzinfo=utc)),
        ),
    ]
