# Generated by Django 2.1.3 on 2020-07-01 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200701_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2020, 7, 1, 3, 44, 5, 175635, tzinfo=utc))),
                ('account', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
            options={
                'db_table': 'new_messages',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 11, 44, 5, 170676, tzinfo=utc)),
        ),
    ]
