# Generated by Django 2.1.3 on 2020-07-02 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200701_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 0, 38, 37, 396053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 16, 38, 37, 401041, tzinfo=utc)),
        ),
    ]
