# Generated by Django 2.1.3 on 2020-07-02 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200703_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 0, 39, 47, 489044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 16, 39, 47, 493034, tzinfo=utc)),
        ),
    ]
