# Generated by Django 2.1.3 on 2020-07-10 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200703_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='check_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 15, 22, 0, 849638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 7, 22, 0, 853627, tzinfo=utc)),
        ),
    ]
