# Generated by Django 2.1.3 on 2020-09-29 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200810_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 15, 9, 18, 828912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 7, 9, 18, 834910, tzinfo=utc)),
        ),
    ]
