# Generated by Django 2.1.3 on 2020-09-29 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200929_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='account',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 15, 53, 18, 477262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 7, 53, 18, 485259, tzinfo=utc)),
        ),
    ]
