# Generated by Django 2.1.3 on 2020-09-29 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200929_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='account',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 16, 3, 5, 59684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 8, 3, 5, 68682, tzinfo=utc)),
        ),
    ]
