# Generated by Django 2.1.3 on 2020-09-29 13:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, max_length=400, null=True)),
                ('country', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=800, null=True)),
                ('last_name', models.CharField(blank=True, max_length=800, null=True)),
                ('address1', models.CharField(blank=True, max_length=800, null=True)),
                ('address2', models.CharField(blank=True, max_length=800, null=True)),
                ('city', models.CharField(blank=True, max_length=800, null=True)),
                ('state', models.CharField(blank=True, max_length=800, null=True)),
                ('country', models.CharField(blank=True, max_length=800, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=800, null=True)),
                ('phone', models.CharField(blank=True, max_length=800, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=800, null=True)),
                ('address2', models.CharField(blank=True, max_length=800, null=True)),
                ('city', models.CharField(blank=True, max_length=800, null=True)),
                ('state', models.CharField(blank=True, max_length=800, null=True)),
                ('country', models.CharField(blank=True, max_length=800, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'group owner'), (2, 'expert'), (3, 'verified')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
